<?php

/**
 * @file
 * Implements hook_field_widget_form_alter().
 */

/**
 * Implements hook_preprocess_HOOK().
 */
function googlecal_sync_preprocess_paragraph__working_hours(&$variables) {
  $working_hours = [];
  $calendar_import = \Drupal::service('googlecal_sync.import_events');
  $calendar_import->validateToken();
  if ($calendar_import->authenticated()) {
    $available_calendars = $calendar_import->getAvailableCalendars();
    foreach ($available_calendars as $calendar) {
      $events = $calendar_import->getTodayEventsList($calendar['id']);
      $working_hours[] = [
        'name' => $calendar['name'],
        "events" => $events,
      ];
    }
  }
  $variables['working_hours'] = $working_hours;
  $variables['#cache']['max-age'] = 0;
}
